<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c327ce52-3923-4ff7-9a50-1213d52d15d8</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_machine_8</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[5]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[17]/td[3]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Remove Machine')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Remove Machine</value>
        <webElementGuid>58a36b4b-fa16-4c3b-a432-13984091bee4</webElementGuid>
    </webElementProperties>
</WebElementEntity>