<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1e047b75-031b-4ca8-83ee-aaa8512343b5</elementGuidId>
    <imagePath></imagePath>
    <name>input_select_a_profile_to_execute_all_rules_in_tha</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/table[1]/tr[1]/td[2]/div[1]/form[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Select a profile to execute all rules in that profile')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Select a profile to execute all rules in that profile</value>
        <webElementGuid>ac5978f7-50d7-472e-b813-a955f8fb680e</webElementGuid>
    </webElementProperties>
</WebElementEntity>