<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa12d5e2-fae8-48fd-81b2-3bfd4bd53b70</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_169</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>