<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b09415c7-e675-4c1c-88ef-efc0d42b45ac</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_101</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[13]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>