<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>63bc908a-6e30-47cc-84cb-5cd28b36102b</elementGuidId>
    <imagePath></imagePath>
    <name>time_06_01_2023_11_39_45_05_30</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[3]/time[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'06/01/2023 11:39:45 +05:30')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>06/01/2023 11:39:45 +05:30</value>
        <webElementGuid>f4914f83-dddc-44db-998d-5c95666a14fc</webElementGuid>
    </webElementProperties>
</WebElementEntity>