<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8caf42ec-0aa0-438e-8827-b9fbb7d4f450</elementGuidId>
    <imagePath></imagePath>
    <name>li_object_40</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[13]/div[1]/div[1]/div[1]/ul[3]/li[23]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>