<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4dc20401-1cf2-4f67-ab04-33fd1cc0e155</elementGuidId>
    <imagePath></imagePath>
    <name>span_test_suites_regression_reclamaciones_android_</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[15]/td[3]/div[2]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/Regression-Reclamaciones(Android)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/Regression-Reclamaciones(Android)</value>
        <webElementGuid>09e21ee4-b922-4dc3-a484-f996fcbe5e65</webElementGuid>
    </webElementProperties>
</WebElementEntity>