<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f303268-6739-4dcd-b044-d28a905e38c9</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_submit_a_support_case</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Submit a Support Case')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Submit a Support Case</value>
        <webElementGuid>5d00f2e0-c744-48e5-86eb-0aff679eef8e</webElementGuid>
    </webElementProperties>
</WebElementEntity>