<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>da5787fe-5159-41d6-9069-2a9f93f2d586</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_submit_a_support_case</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Submit a Support Case')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Submit a Support Case</value>
        <webElementGuid>5b740661-ec48-45a0-b1ff-10af1bbcbb48</webElementGuid>
    </webElementProperties>
</WebElementEntity>