<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c0da396d-b52f-4c60-b7db-452a39ce047d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_testcloud_tunnels</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='TestCloud\ Tunnels']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'nav-link') and equals(@title,'TestCloud Tunnels')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>nav-link</value>
        <webElementGuid>cdaafc8f-42e7-4204-a7a4-59392db0be63</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>TestCloud Tunnels</value>
        <webElementGuid>66ae8707-1741-4830-9dcf-3c5a5a1758d1</webElementGuid>
    </webElementProperties>
</WebElementEntity>