<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b51cb488-cc11-46d1-ab90-52dd7645cad2</elementGuidId>
    <imagePath></imagePath>
    <name>li_tablet</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[1]/div[1]/div[1]/ul[3]/li[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Tablet')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Tablet</value>
        <webElementGuid>7da4edd8-b553-4e81-aa5e-a2089cb55ac0</webElementGuid>
    </webElementProperties>
</WebElementEntity>