<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2a0b35f6-f3dc-47b4-bcb5-1309561ac9a6</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_30</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>