<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0c9c6b6b-8897-4328-90a0-ef948fb6c904</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_test_cases</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='Test\ Cases']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'nav-link') and equals(@title,'Test Cases')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>nav-link</value>
        <webElementGuid>3e87ae1b-e86c-45e3-b523-97549d388d03</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Cases</value>
        <webElementGuid>f7f473ff-9e90-4d0a-b272-103f9d1493f3</webElementGuid>
    </webElementProperties>
</WebElementEntity>