<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>56324cb8-369f-4040-a1e5-fe3f51444722</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_test_cases</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'nav-link') and equals(@title,'Test Cases')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>nav-link</value>
        <webElementGuid>b05ea979-efeb-48c5-a3c1-c0797ad9811f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Cases</value>
        <webElementGuid>78f45c59-971b-4981-b141-b457ceb5df52</webElementGuid>
    </webElementProperties>
</WebElementEntity>