<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>12b1ca38-afc6-4ed3-b0bc-5ad694363d0e</elementGuidId>
    <imagePath></imagePath>
    <name>button_recent_work</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Recent Work')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Recent Work</value>
        <webElementGuid>cb68f79b-b1d0-49d2-ac76-89dcc362cedd</webElementGuid>
    </webElementProperties>
</WebElementEntity>