<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7d7d97b0-f2e3-479f-93cf-31460aa97960</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_test_cases_regression_hra_hraeligibletab</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[15]/td[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Cases/Regression/HRA/HRAEligibleTab')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Cases/Regression/HRA/HRAEligibleTab</value>
        <webElementGuid>689ddcdd-f36e-4a7e-81d6-e7310f6b8c8a</webElementGuid>
    </webElementProperties>
</WebElementEntity>