<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>070833c9-74d2-42f6-b560-34c959b1bdf3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_test_cases_tests_functional_regression_t_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[20]/td[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Cases/Tests/Functional Regression Tests/WC_NewEnhancement/TS20_AUTO_PC_WC_CR66_NB_UWIssue_WI')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Cases/Tests/Functional Regression Tests/WC_NewEnhancement/TS20_AUTO_PC_WC_CR66_NB_UWIssue_WI</value>
        <webElementGuid>562c923e-d998-4237-b0d6-71c61a2e478c</webElementGuid>
    </webElementProperties>
</WebElementEntity>