<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>82624969-60b4-4cd3-94c6-3b4eae21a647</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_20</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>