<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>14f01fba-4694-40f7-8c2c-3d644b78f63b</elementGuidId>
    <imagePath></imagePath>
    <name>div_test_suites_regression_grouped_webui_regressio</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[7]/td[4]/div[2]/div[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/Regression/Grouped/WebUI Regression Test Prerequisites')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/Regression/Grouped/WebUI Regression Test Prerequisites</value>
        <webElementGuid>554ef85b-47ed-4f1b-8f37-517cc0e9400c</webElementGuid>
    </webElementProperties>
</WebElementEntity>