<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cdd4d037-ae8e-4f33-9d23-faf506518ee6</elementGuidId>
    <imagePath></imagePath>
    <name>span_test_suites_03_executioncompletemaster_clean</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[4]/td[3]/div[2]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/03_ExecutionCompleteMaster-clean')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/03_ExecutionCompleteMaster-clean</value>
        <webElementGuid>13e13a57-1968-402a-bca5-4b9c7efc8a96</webElementGuid>
    </webElementProperties>
</WebElementEntity>