<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2aef0a41-a8e0-4da5-82dc-cfcb4f27d56e</elementGuidId>
    <imagePath></imagePath>
    <name>span_test_suites_mobile_android_login_ts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/table[1]/tbody[1]/tr[3]/td[4]/div[1]/div[1]/div[1]/div[1]/span[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/mobile/android/login_ts')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/mobile/android/login_ts</value>
        <webElementGuid>72116985-18ef-4dbd-943a-0bcc2deb9904</webElementGuid>
    </webElementProperties>
</WebElementEntity>