<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b2ef9a9b-80ef-470c-be51-6494b48cc22d</elementGuidId>
    <imagePath></imagePath>
    <name>time_05_30_2023_22_06_15_04_00</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[16]/td[6]/span[2]/time[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'05/30/2023 22:06:15 -04:00')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>05/30/2023 22:06:15 -04:00</value>
        <webElementGuid>c0b4a0da-00d5-4c64-b21e-b8b5854105ff</webElementGuid>
    </webElementProperties>
</WebElementEntity>