<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3c247cbf-9a17-471c-bcdc-a69dcc3fa24f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_view_usage_dashboard_of_katalon_studio_a</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'View usage dashboard of Katalon Studio and TestOps.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>View usage dashboard of Katalon Studio and TestOps.</value>
        <webElementGuid>c7b321cc-d0f2-4bbe-ba39-9817d2fc8de4</webElementGuid>
    </webElementProperties>
</WebElementEntity>