<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6fae5b8c-1a42-4ced-9c74-0d428aea4bf4</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_85</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[11]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>