<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>11af2e5f-ba01-42f9-ae94-3668cdab4fd8</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_119</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>