<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ee0f2d1e-9958-49fb-bf54-0344ee333b1e</elementGuidId>
    <imagePath></imagePath>
    <name>div_permissions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[1]/ul[1]/li[1]/ul[1]/li[5]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Permissions')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Permissions</value>
        <webElementGuid>c2f8af0b-4528-4123-8e98-c08ce6aeef37</webElementGuid>
    </webElementProperties>
</WebElementEntity>