<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9850500b-388e-40a5-a66e-0c437e48240f</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_132</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/table[1]/thead[1]/tr[1]/th[8]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>