<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8473e1bd-80f1-45d0-b781-2ebfd3c320b4</elementGuidId>
    <imagePath></imagePath>
    <name>span_chrome_114_0_0_0_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[4]/span[1]/span[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Chrome 114.0.0.0')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Chrome 114.0.0.0</value>
        <webElementGuid>2777c194-2e15-4711-8b48-e61526f494d2</webElementGuid>
    </webElementProperties>
</WebElementEntity>