<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e9770c4d-f194-453a-af9f-67542511d4df</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_view_usage_dashboard_of_katalon_studio_a_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[3]/nav[1]/div[1]/ul[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'View usage dashboard of Katalon Studio and TestOps.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>View usage dashboard of Katalon Studio and TestOps.</value>
        <webElementGuid>02989175-7890-42a2-abfa-a432103fa712</webElementGuid>
    </webElementProperties>
</WebElementEntity>