<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9dac2e68-60f3-42be-a175-c9d743e3656b</elementGuidId>
    <imagePath></imagePath>
    <name>span_test_suites_ts_katalon_health_care_ts_book_an</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[12]/td[4]/div[1]/div[1]/div[1]/div[1]/span[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/TS Katalon Health Care/TS_Book an Agent')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/TS Katalon Health Care/TS_Book an Agent</value>
        <webElementGuid>456f04d9-7e34-4fdc-a8b8-aeeb7260b35c</webElementGuid>
    </webElementProperties>
</WebElementEntity>