<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0994498-9303-4db8-8b90-24d8f4a5b4da</elementGuidId>
    <imagePath></imagePath>
    <name>time_06_13_2023_13_42_52_04_00</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[6]/span[2]/time[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'06/13/2023 13:42:52 -04:00')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>06/13/2023 13:42:52 -04:00</value>
        <webElementGuid>7369994f-1718-4d2d-b8d2-2ff01fac021b</webElementGuid>
    </webElementProperties>
</WebElementEntity>