<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>26e2b05b-9e80-4738-a9b2-efac6a69e950</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_update_project_information_and_other_sec_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[10]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Update project information and other security configurations.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Update project information and other security configurations.</value>
        <webElementGuid>46b5da3f-d997-4a38-adb0-ff6c153eb740</webElementGuid>
    </webElementProperties>
</WebElementEntity>