<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>71369740-7c89-4e3d-b516-b5be40aef97c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_create_teams_and_manage_teams_</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[3]/nav[1]/div[1]/ul[1]/a[8]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Create teams and manage teams.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Create teams and manage teams.</value>
        <webElementGuid>88478ba8-ce6b-4fb9-be1c-f1b8b2a5b1f2</webElementGuid>
    </webElementProperties>
</WebElementEntity>