<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>19dc308e-3617-4f45-8298-82db0fcc4a3d</elementGuidId>
    <imagePath></imagePath>
    <name>button_victor_sen</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'victor sen')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>victor sen</value>
        <webElementGuid>60b979cc-8550-46c5-96ec-b6bf04929aa2</webElementGuid>
    </webElementProperties>
</WebElementEntity>