<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ea6d92c7-2438-4e8e-9682-6e88d33bd6c2</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_machine</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[5]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Remove Machine')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Remove Machine</value>
        <webElementGuid>d2e544b2-f8d0-4c10-a929-26577b5d68fc</webElementGuid>
    </webElementProperties>
</WebElementEntity>