<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8e4a50d5-ce4c-4af0-95e4-4be7565dbb94</elementGuidId>
    <imagePath></imagePath>
    <name>font_object_16</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//html/div[1]/div[1]/div[2]/div[2]/div[1]/span[1]/font[1]/font[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>