<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6b35f5c2-ea77-434c-9f47-7dcb65ea5d23</elementGuidId>
    <imagePath></imagePath>
    <name>font_object_19</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/table[1]/thead[1]/tr[1]/th[2]/font[1]/font[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>