<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ba883c4d-e967-4b9d-afc6-bc7bb0bf64f8</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_edit_organization_information_and_manage_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[3]/nav[1]/div[1]/ul[1]/a[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Edit organization information and manage security.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Edit organization information and manage security.</value>
        <webElementGuid>213abda9-637d-4eac-9da1-61856f73a9a0</webElementGuid>
    </webElementProperties>
</WebElementEntity>