<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>645e440d-bb9f-48b1-9af3-bc817b316b46</elementGuidId>
    <imagePath></imagePath>
    <name>div_create_kre_floating_license</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Create KRE Floating License')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Create KRE Floating License</value>
        <webElementGuid>c4b90d45-b038-4af4-a06e-ac8619292c6a</webElementGuid>
    </webElementProperties>
</WebElementEntity>