<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5a0c5358-29fa-435d-98c4-1599805c2ee5</elementGuidId>
    <imagePath></imagePath>
    <name>button_close_survey</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Close survey')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Close survey</value>
        <webElementGuid>39b3c39b-2d6d-4117-ab7d-6929891a8965</webElementGuid>
    </webElementProperties>
</WebElementEntity>