<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6ccfd6bc-10af-449b-8fb2-b9677a055b31</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_31</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>