<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a5994def-ffee-43e2-9f5f-6aea642af1da</elementGuidId>
    <imagePath></imagePath>
    <name>input_webhook_name_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[13]/div[3]/div[1]/form[1]/div[1]/p[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'webhook-name')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>webhook-name</value>
        <webElementGuid>a79775db-f546-4092-a7ad-c46b1f20d0b0</webElementGuid>
    </webElementProperties>
</WebElementEntity>