<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d2fd43fa-f988-4027-98b2-a986878f1395</elementGuidId>
    <imagePath></imagePath>
    <name>select_within_unit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[1]/ul[1]/form[1]/li[1]/div[1]/label[1]/span[2]/div[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'withIn.unit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>withIn.unit</value>
        <webElementGuid>e4585e9f-cc71-443c-a3b5-bb3a5cd40c5d</webElementGuid>
    </webElementProperties>
</WebElementEntity>