<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6f604ae9-d8a8-4a3b-8b3d-740afe3740b0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_settings_switch_account_desc</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[3]/nav[1]/div[1]/ul[1]/a[6]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'settings-switch-account-desc')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>settings-switch-account-desc</value>
        <webElementGuid>a4e2038e-ff5d-4c2c-abcd-417710f11f9d</webElementGuid>
    </webElementProperties>
</WebElementEntity>