<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e89e3869-6de4-4f97-9359-182539912f7f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_ajustes_de_usuario</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[3]/nav[1]/div[1]/ul[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Ajustes de usuario')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Ajustes de usuario</value>
        <webElementGuid>4833a874-7544-4fb9-a7f5-6570be9b860c</webElementGuid>
    </webElementProperties>
</WebElementEntity>