<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>adba4054-3b76-4879-8647-de4096aad8bd</elementGuidId>
    <imagePath></imagePath>
    <name>span_chrome</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/div[2]/div[1]/div[4]/div[2]/div[2]/div[1]/div[2]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Chrome')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Chrome</value>
        <webElementGuid>32c631f3-5d3c-438a-8d90-23dd150f4930</webElementGuid>
    </webElementProperties>
</WebElementEntity>