<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>190d0641-cff6-470f-9d81-781258dfb27c</elementGuidId>
    <imagePath></imagePath>
    <name>span_test_suites_prioritytestcollections_priority1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[6]/td[3]/div[2]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/PriorityTestCollections/Priority1TestCases')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/PriorityTestCollections/Priority1TestCases</value>
        <webElementGuid>7ad1fcd0-88b1-474a-ac40-400a45fc7741</webElementGuid>
    </webElementProperties>
</WebElementEntity>