<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ec631f72-bf2d-4c1e-ada2-d0f524e04a76</elementGuidId>
    <imagePath></imagePath>
    <name>button_settings</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Settings')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Settings</value>
        <webElementGuid>cbdf1129-9fde-4e6a-a24b-867742414b5c</webElementGuid>
    </webElementProperties>
</WebElementEntity>