<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f90a8e9d-0ba3-4576-96ae-3102f173be4a</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_machine_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[5]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Remove Machine')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Remove Machine</value>
        <webElementGuid>028c5590-3eff-49b1-8744-2f5c6d9d6612</webElementGuid>
    </webElementProperties>
</WebElementEntity>